package com.snail.pojo.domain;

import java.util.Date;

public class Experience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.stage_time
     *
     * @mbggenerated
     */
    private Date stageTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.jump_url
     *
     * @mbggenerated
     */
    private String jumpUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.icon_src
     *
     * @mbggenerated
     */
    private String iconSrc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    public Experience(Integer id, Date stageTime, String title, String content, String jumpUrl, String iconSrc) {
        this.id = id;
        this.stageTime = stageTime;
        this.title = title;
        this.content = content;
        this.jumpUrl = jumpUrl;
        this.iconSrc = iconSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    public Experience() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.id
     *
     * @return the value of experience.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.id
     *
     * @param id the value for experience.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.stage_time
     *
     * @return the value of experience.stage_time
     *
     * @mbggenerated
     */
    public Date getStageTime() {
        return stageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.stage_time
     *
     * @param stageTime the value for experience.stage_time
     *
     * @mbggenerated
     */
    public void setStageTime(Date stageTime) {
        this.stageTime = stageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.title
     *
     * @return the value of experience.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.title
     *
     * @param title the value for experience.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.content
     *
     * @return the value of experience.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.content
     *
     * @param content the value for experience.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.jump_url
     *
     * @return the value of experience.jump_url
     *
     * @mbggenerated
     */
    public String getJumpUrl() {
        return jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.jump_url
     *
     * @param jumpUrl the value for experience.jump_url
     *
     * @mbggenerated
     */
    public void setJumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl == null ? null : jumpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.icon_src
     *
     * @return the value of experience.icon_src
     *
     * @mbggenerated
     */
    public String getIconSrc() {
        return iconSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.icon_src
     *
     * @param iconSrc the value for experience.icon_src
     *
     * @mbggenerated
     */
    public void setIconSrc(String iconSrc) {
        this.iconSrc = iconSrc == null ? null : iconSrc.trim();
    }
}