package com.snail.dao;

import com.snail.pojo.domain.Experience;
import com.snail.pojo.domain.ExperienceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ExperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    int countByExample(ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    int deleteByExample(ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `experience`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `experience` (`id`, `stage_time`, ",
        "`title`, `content`, ",
        "`jump_url`, `icon_src`)",
        "values (#{id,jdbcType=INTEGER}, #{stageTime,jdbcType=TIMESTAMP}, ",
        "#{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{jumpUrl,jdbcType=VARCHAR}, #{iconSrc,jdbcType=VARCHAR})"
    })
    int insert(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    int insertSelective(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    List<Experience> selectByExample(ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `stage_time`, `title`, `content`, `jump_url`, `icon_src`",
        "from `experience`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Experience selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Experience record, @Param("example") ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Experience record, @Param("example") ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated
     */
    @Update({
        "update `experience`",
        "set `stage_time` = #{stageTime,jdbcType=TIMESTAMP},",
          "`title` = #{title,jdbcType=VARCHAR},",
          "`content` = #{content,jdbcType=VARCHAR},",
          "`jump_url` = #{jumpUrl,jdbcType=VARCHAR},",
          "`icon_src` = #{iconSrc,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Experience record);
}